//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/New test_3d/player_controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_controller : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_controller()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""player_controller"",
    ""maps"": [
        {
            ""name"": ""player movement"",
            ""id"": ""f330cbc9-c06c-4207-be6b-fd509e4087b1"",
            ""actions"": [
                {
                    ""name"": ""movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c02f9f37-5982-4fa7-9688-a3c0e24ef144"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5884280b-f9b2-45b6-96d2-ad6c951ae6a1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""wasd"",
                    ""id"": ""dec02620-b72d-4ad8-9f2c-0e77a02a0e43"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d2f29006-4eb0-402a-9eeb-28edc71ef1ed"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c50b6fa2-f204-491a-99ca-28a8a807106f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""89c134e3-11d2-48e0-a09d-cf90db293b88"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c7029b4c-af2d-4dd8-8f06-d5afe50d9cdb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""71679469-6123-4e4b-afa3-4e6a3c7ea8a7"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77f6a723-ca1c-4e84-a289-4b4bd3b43ccc"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""player actions"",
            ""id"": ""1eda179f-dd1d-41e6-b839-04512ee028a8"",
            ""actions"": [
                {
                    ""name"": ""roll"",
                    ""type"": ""Button"",
                    ""id"": ""0c44deb2-353c-4b16-8105-0b25681eda0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RB"",
                    ""type"": ""Button"",
                    ""id"": ""9d12f432-bdfc-4a50-9a31-374c393bcf61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RT"",
                    ""type"": ""Button"",
                    ""id"": ""bb0ac829-fb83-4532-aba3-69baad4a7037"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""d8194c34-2842-41e9-8a5c-9356fdfec11e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JUMP"",
                    ""type"": ""Button"",
                    ""id"": ""4f8b561f-9ea2-4d41-bbe6-be8cc66a4f5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d625eb85-b9a3-4b8a-9234-1e65d0e7bc92"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7f8a0ea-6651-4ceb-9459-8f57baa60895"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcec323f-d007-401b-aa7a-7dc04efcda91"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8db697d2-0471-4afb-b54a-72c803558e17"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c729593f-30b5-4a5d-9d1e-2976379411c3"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f1a8bfb-8394-4131-a880-1241b67374ca"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bb1bf5a-3e7d-4ea5-889f-4975a8a29383"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27c1426b-c980-4d12-985f-aefbcc659f08"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""player quick slots"",
            ""id"": ""24e599af-68e8-4a47-acf7-49b4b48f5578"",
            ""actions"": [
                {
                    ""name"": ""D-Pad-Up"",
                    ""type"": ""Button"",
                    ""id"": ""9f943590-d615-469d-9e5c-59150abbf02a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D-Pad-Down"",
                    ""type"": ""Button"",
                    ""id"": ""36f28ecc-d24c-4a2a-ace1-0dda9891783c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D-Pad-Right"",
                    ""type"": ""Button"",
                    ""id"": ""af973faf-6c7b-47ab-bfb7-a9c6847dd573"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""D-Pad-Left"",
                    ""type"": ""Button"",
                    ""id"": ""0b641fc4-91ad-4ac7-a48f-de67b1583a75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e71e063-270e-4465-b7e0-3a1237637737"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86c39406-8f5c-4a66-8f37-ce4212c36aa6"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e72e3f85-9df5-4f7d-b7bf-a6afff673bb4"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b42dfdfc-006c-4817-8f8b-e3be576e1502"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e5baec8-1fec-4921-a8cc-ee387750c9a7"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a732eb9-ce07-416b-8dfc-7846abb87ee7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""885cd886-77a2-45b2-8d0c-0dd0f46f9f7d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf8c394d-3f46-4589-9af8-69f25fa7c255"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""D-Pad-Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // player movement
        m_playermovement = asset.FindActionMap("player movement", throwIfNotFound: true);
        m_playermovement_movement = m_playermovement.FindAction("movement", throwIfNotFound: true);
        m_playermovement_camera = m_playermovement.FindAction("camera", throwIfNotFound: true);
        // player actions
        m_playeractions = asset.FindActionMap("player actions", throwIfNotFound: true);
        m_playeractions_roll = m_playeractions.FindAction("roll", throwIfNotFound: true);
        m_playeractions_RB = m_playeractions.FindAction("RB", throwIfNotFound: true);
        m_playeractions_RT = m_playeractions.FindAction("RT", throwIfNotFound: true);
        m_playeractions_A = m_playeractions.FindAction("A", throwIfNotFound: true);
        m_playeractions_JUMP = m_playeractions.FindAction("JUMP", throwIfNotFound: true);
        // player quick slots
        m_playerquickslots = asset.FindActionMap("player quick slots", throwIfNotFound: true);
        m_playerquickslots_DPadUp = m_playerquickslots.FindAction("D-Pad-Up", throwIfNotFound: true);
        m_playerquickslots_DPadDown = m_playerquickslots.FindAction("D-Pad-Down", throwIfNotFound: true);
        m_playerquickslots_DPadRight = m_playerquickslots.FindAction("D-Pad-Right", throwIfNotFound: true);
        m_playerquickslots_DPadLeft = m_playerquickslots.FindAction("D-Pad-Left", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player movement
    private readonly InputActionMap m_playermovement;
    private IPlayermovementActions m_PlayermovementActionsCallbackInterface;
    private readonly InputAction m_playermovement_movement;
    private readonly InputAction m_playermovement_camera;
    public struct PlayermovementActions
    {
        private @Player_controller m_Wrapper;
        public PlayermovementActions(@Player_controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @movement => m_Wrapper.m_playermovement_movement;
        public InputAction @camera => m_Wrapper.m_playermovement_camera;
        public InputActionMap Get() { return m_Wrapper.m_playermovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayermovementActions set) { return set.Get(); }
        public void SetCallbacks(IPlayermovementActions instance)
        {
            if (m_Wrapper.m_PlayermovementActionsCallbackInterface != null)
            {
                @movement.started -= m_Wrapper.m_PlayermovementActionsCallbackInterface.OnMovement;
                @movement.performed -= m_Wrapper.m_PlayermovementActionsCallbackInterface.OnMovement;
                @movement.canceled -= m_Wrapper.m_PlayermovementActionsCallbackInterface.OnMovement;
                @camera.started -= m_Wrapper.m_PlayermovementActionsCallbackInterface.OnCamera;
                @camera.performed -= m_Wrapper.m_PlayermovementActionsCallbackInterface.OnCamera;
                @camera.canceled -= m_Wrapper.m_PlayermovementActionsCallbackInterface.OnCamera;
            }
            m_Wrapper.m_PlayermovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @movement.started += instance.OnMovement;
                @movement.performed += instance.OnMovement;
                @movement.canceled += instance.OnMovement;
                @camera.started += instance.OnCamera;
                @camera.performed += instance.OnCamera;
                @camera.canceled += instance.OnCamera;
            }
        }
    }
    public PlayermovementActions @playermovement => new PlayermovementActions(this);

    // player actions
    private readonly InputActionMap m_playeractions;
    private IPlayeractionsActions m_PlayeractionsActionsCallbackInterface;
    private readonly InputAction m_playeractions_roll;
    private readonly InputAction m_playeractions_RB;
    private readonly InputAction m_playeractions_RT;
    private readonly InputAction m_playeractions_A;
    private readonly InputAction m_playeractions_JUMP;
    public struct PlayeractionsActions
    {
        private @Player_controller m_Wrapper;
        public PlayeractionsActions(@Player_controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @roll => m_Wrapper.m_playeractions_roll;
        public InputAction @RB => m_Wrapper.m_playeractions_RB;
        public InputAction @RT => m_Wrapper.m_playeractions_RT;
        public InputAction @A => m_Wrapper.m_playeractions_A;
        public InputAction @JUMP => m_Wrapper.m_playeractions_JUMP;
        public InputActionMap Get() { return m_Wrapper.m_playeractions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayeractionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayeractionsActions instance)
        {
            if (m_Wrapper.m_PlayeractionsActionsCallbackInterface != null)
            {
                @roll.started -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRoll;
                @roll.performed -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRoll;
                @roll.canceled -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRoll;
                @RB.started -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRB;
                @RB.performed -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRB;
                @RB.canceled -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRB;
                @RT.started -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRT;
                @RT.performed -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRT;
                @RT.canceled -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnRT;
                @A.started -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnA;
                @JUMP.started -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnJUMP;
                @JUMP.performed -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnJUMP;
                @JUMP.canceled -= m_Wrapper.m_PlayeractionsActionsCallbackInterface.OnJUMP;
            }
            m_Wrapper.m_PlayeractionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @roll.started += instance.OnRoll;
                @roll.performed += instance.OnRoll;
                @roll.canceled += instance.OnRoll;
                @RB.started += instance.OnRB;
                @RB.performed += instance.OnRB;
                @RB.canceled += instance.OnRB;
                @RT.started += instance.OnRT;
                @RT.performed += instance.OnRT;
                @RT.canceled += instance.OnRT;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @JUMP.started += instance.OnJUMP;
                @JUMP.performed += instance.OnJUMP;
                @JUMP.canceled += instance.OnJUMP;
            }
        }
    }
    public PlayeractionsActions @playeractions => new PlayeractionsActions(this);

    // player quick slots
    private readonly InputActionMap m_playerquickslots;
    private IPlayerquickslotsActions m_PlayerquickslotsActionsCallbackInterface;
    private readonly InputAction m_playerquickslots_DPadUp;
    private readonly InputAction m_playerquickslots_DPadDown;
    private readonly InputAction m_playerquickslots_DPadRight;
    private readonly InputAction m_playerquickslots_DPadLeft;
    public struct PlayerquickslotsActions
    {
        private @Player_controller m_Wrapper;
        public PlayerquickslotsActions(@Player_controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @DPadUp => m_Wrapper.m_playerquickslots_DPadUp;
        public InputAction @DPadDown => m_Wrapper.m_playerquickslots_DPadDown;
        public InputAction @DPadRight => m_Wrapper.m_playerquickslots_DPadRight;
        public InputAction @DPadLeft => m_Wrapper.m_playerquickslots_DPadLeft;
        public InputActionMap Get() { return m_Wrapper.m_playerquickslots; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerquickslotsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerquickslotsActions instance)
        {
            if (m_Wrapper.m_PlayerquickslotsActionsCallbackInterface != null)
            {
                @DPadUp.started -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadUp;
                @DPadUp.performed -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadUp;
                @DPadUp.canceled -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadUp;
                @DPadDown.started -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadDown;
                @DPadDown.performed -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadDown;
                @DPadDown.canceled -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadDown;
                @DPadRight.started -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadRight;
                @DPadRight.performed -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadRight;
                @DPadRight.canceled -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadRight;
                @DPadLeft.started -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.performed -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.canceled -= m_Wrapper.m_PlayerquickslotsActionsCallbackInterface.OnDPadLeft;
            }
            m_Wrapper.m_PlayerquickslotsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @DPadUp.started += instance.OnDPadUp;
                @DPadUp.performed += instance.OnDPadUp;
                @DPadUp.canceled += instance.OnDPadUp;
                @DPadDown.started += instance.OnDPadDown;
                @DPadDown.performed += instance.OnDPadDown;
                @DPadDown.canceled += instance.OnDPadDown;
                @DPadRight.started += instance.OnDPadRight;
                @DPadRight.performed += instance.OnDPadRight;
                @DPadRight.canceled += instance.OnDPadRight;
                @DPadLeft.started += instance.OnDPadLeft;
                @DPadLeft.performed += instance.OnDPadLeft;
                @DPadLeft.canceled += instance.OnDPadLeft;
            }
        }
    }
    public PlayerquickslotsActions @playerquickslots => new PlayerquickslotsActions(this);
    public interface IPlayermovementActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
    }
    public interface IPlayeractionsActions
    {
        void OnRoll(InputAction.CallbackContext context);
        void OnRB(InputAction.CallbackContext context);
        void OnRT(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnJUMP(InputAction.CallbackContext context);
    }
    public interface IPlayerquickslotsActions
    {
        void OnDPadUp(InputAction.CallbackContext context);
        void OnDPadDown(InputAction.CallbackContext context);
        void OnDPadRight(InputAction.CallbackContext context);
        void OnDPadLeft(InputAction.CallbackContext context);
    }
}
